# config/app.yml for rails-settings-cached
defaults: &defaults
  site_title: 'Hacker Tribe'
  site_description: 'Community of Hackers and Founders'
  site_extended_description: 'This is a community for people who are interested in startups, programming, science, and tech. Our goal is to share and discuss insighful ideas that gratify intellectual curiosity, share our experience, and help each other to make awesome things.'
  site_contact_username: 'rayalez'
  site_contact_email: 'raymestalez@gmail.com'
  open_registrations: true
  closed_registrations_message: ''
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
  interactions:
    must_be_follower: false
    must_be_following: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
